apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jb-springboot
  template:
    metadata:
      labels:
        app: jb-springboot
    spec:
      containers:
        - name: springboot
          image: jonebabu2/integration:jb-docker-demo1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jb-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jb-springboot
